Multiple aws profiles
BishopFox/cloudfox pull request #8
Opened 2022-09-24 03:11 UTC by PrestigeTicko

#### Card

Implemented support for multiple AWS profiles via a text file of multiple profiles separated by new lines or simply asking cloudfox to use all profiles in the credentials file. 

#### Details

* The init function of cli/aws.go has a call to a new function called initAWSProfiles which sets values to a slice of strings which is used as the AWS profiles to be used for the remaining commands. 
* The initAWSProfiles function at cli/aws.go:855 ensures that only one option of list of profiles, one profile, or all profiles is selected. It then uses the new util functions to get the AWS profiles from a given file or the default AWS credentials file. As noted in the readme of cloudfox, this functionality also assumes the user will have an AWS credentials file in place. When neither of -p, --profiles-list (new), or --all-profiles (new) is selected and empty string is passed and existing functionality takes care of using the AWS environment variables or the default profile.
*  The two helper functions that are used in initAWSProfiles are utils.GetSelectedAWSProfiles and utils.GetAllAWSProfiles. Both do what their names suggest and I have included tests in utils/aws_test.go.
* To accommodate multiple profiles I simply wrapped a for loop iterating over the list of profiles around every function call. Thats it :)
* The --all-profiles / -a and --profiles-list / -l flags were added.
* Some modules were updated in the process and I also updated a small logging statement in AWSConfigFileLoader in utils/aws.go so that it would specify the given profile its having trouble reading.

2022-09-26 04:28 UTC, B-Eazy6680 requested changes
EDITED: removing content because of SPAM.

2022-10-04 04:45 UTC, B-Eazy6680 reviewed
- [ ]

2022-10-04 04:45 UTC, B-Eazy6680 commented on go.mod
>  	github.com/aws/aws-sdk-go-v2/config v1.13.0
Why

2022-10-04 04:45 UTC, B-Eazy6680 commented on go.mod
>  	github.com/aws/aws-sdk-go-v2/service/apigateway v1.15.6
**[]()[]()[]()[]()**

2022-10-05 18:22 UTC, sethsec-bf commented
- For `--all-profiles`, added check for profiles in config (in addition to credentials)
- For `--all-profiles`, added a default interactive sanity check to display all profiles and confirm you wan't to really do it
- For `--all-profiles`, added a `-y` flag for non-interactive mode so you can skip the interactive prompt if running in a script
- Updated error messages to include which profile failed
- Added a way for cloudfox to continue in multi-profile mode if one of the many profiles fails

2022-10-05 18:23 UTC, sethsec-bf approved these changes

2022-10-05 18:27 UTC, merged